/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as MarketingRouteRouteImport } from './routes/_marketing/route'
import { Route as MarketingIndexRouteImport } from './routes/_marketing/index'
import { Route as AdminSetupRouteImport } from './routes/admin/setup'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as MarketingContactRouteImport } from './routes/_marketing/contact'
import { Route as MarketingApplicationRouteImport } from './routes/_marketing/application'
import { Route as MarketingAboutRouteImport } from './routes/_marketing/about'
import { Route as AdminDashboardRouteRouteImport } from './routes/admin/_dashboard/route'
import { Route as AdminDashboardIndexRouteImport } from './routes/admin/_dashboard/index'
import { Route as MarketingDogsIndexRouteImport } from './routes/_marketing/dogs/index'
import { Route as ApiRpcSplatRouteImport } from './routes/api/rpc.$'
import { Route as ApiImagesSplatRouteImport } from './routes/api/images/$'
import { Route as ApiAuthSetupRouteImport } from './routes/api/auth/setup'
import { Route as ApiAuthLogoutRouteImport } from './routes/api/auth/logout'
import { Route as ApiAuthLoginRouteImport } from './routes/api/auth/login'
import { Route as AdminDashboardMediaRouteImport } from './routes/admin/_dashboard/media'
import { Route as MarketingDogsDogIdRouteImport } from './routes/_marketing/dogs/$dogId'
import { Route as AdminDashboardApplicationsRouteRouteImport } from './routes/admin/_dashboard/applications/route'
import { Route as AdminDashboardApplicationsIndexRouteImport } from './routes/admin/_dashboard/applications/index'
import { Route as AdminDashboardDogsNewRouteImport } from './routes/admin/_dashboard/dogs/new'
import { Route as AdminDashboardDogsDogIdEditRouteImport } from './routes/admin/_dashboard/dogs/$dogId.edit'

const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingRouteRoute = MarketingRouteRouteImport.update({
  id: '/_marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingIndexRoute = MarketingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MarketingRouteRoute,
} as any)
const AdminSetupRoute = AdminSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRouteRoute,
} as any)
const MarketingContactRoute = MarketingContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => MarketingRouteRoute,
} as any)
const MarketingApplicationRoute = MarketingApplicationRouteImport.update({
  id: '/application',
  path: '/application',
  getParentRoute: () => MarketingRouteRoute,
} as any)
const MarketingAboutRoute = MarketingAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => MarketingRouteRoute,
} as any)
const AdminDashboardRouteRoute = AdminDashboardRouteRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminDashboardIndexRoute = AdminDashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminDashboardRouteRoute,
} as any)
const MarketingDogsIndexRoute = MarketingDogsIndexRouteImport.update({
  id: '/dogs/',
  path: '/dogs/',
  getParentRoute: () => MarketingRouteRoute,
} as any)
const ApiRpcSplatRoute = ApiRpcSplatRouteImport.update({
  id: '/api/rpc/$',
  path: '/api/rpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiImagesSplatRoute = ApiImagesSplatRouteImport.update({
  id: '/api/images/$',
  path: '/api/images/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSetupRoute = ApiAuthSetupRouteImport.update({
  id: '/api/auth/setup',
  path: '/api/auth/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLogoutRoute = ApiAuthLogoutRouteImport.update({
  id: '/api/auth/logout',
  path: '/api/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLoginRoute = ApiAuthLoginRouteImport.update({
  id: '/api/auth/login',
  path: '/api/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardMediaRoute = AdminDashboardMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AdminDashboardRouteRoute,
} as any)
const MarketingDogsDogIdRoute = MarketingDogsDogIdRouteImport.update({
  id: '/dogs/$dogId',
  path: '/dogs/$dogId',
  getParentRoute: () => MarketingRouteRoute,
} as any)
const AdminDashboardApplicationsRouteRoute =
  AdminDashboardApplicationsRouteRouteImport.update({
    id: '/applications',
    path: '/applications',
    getParentRoute: () => AdminDashboardRouteRoute,
  } as any)
const AdminDashboardApplicationsIndexRoute =
  AdminDashboardApplicationsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdminDashboardApplicationsRouteRoute,
  } as any)
const AdminDashboardDogsNewRoute = AdminDashboardDogsNewRouteImport.update({
  id: '/dogs/new',
  path: '/dogs/new',
  getParentRoute: () => AdminDashboardRouteRoute,
} as any)
const AdminDashboardDogsDogIdEditRoute =
  AdminDashboardDogsDogIdEditRouteImport.update({
    id: '/dogs/$dogId/edit',
    path: '/dogs/$dogId/edit',
    getParentRoute: () => AdminDashboardRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof MarketingIndexRoute
  '/admin': typeof AdminDashboardRouteRouteWithChildren
  '/about': typeof MarketingAboutRoute
  '/application': typeof MarketingApplicationRoute
  '/contact': typeof MarketingContactRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/setup': typeof AdminSetupRoute
  '/admin/applications': typeof AdminDashboardApplicationsRouteRouteWithChildren
  '/dogs/$dogId': typeof MarketingDogsDogIdRoute
  '/admin/media': typeof AdminDashboardMediaRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/setup': typeof ApiAuthSetupRoute
  '/api/images/$': typeof ApiImagesSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/dogs/': typeof MarketingDogsIndexRoute
  '/admin/': typeof AdminDashboardIndexRoute
  '/admin/dogs/new': typeof AdminDashboardDogsNewRoute
  '/admin/applications/': typeof AdminDashboardApplicationsIndexRoute
  '/admin/dogs/$dogId/edit': typeof AdminDashboardDogsDogIdEditRoute
}
export interface FileRoutesByTo {
  '/admin': typeof AdminDashboardIndexRoute
  '/about': typeof MarketingAboutRoute
  '/application': typeof MarketingApplicationRoute
  '/contact': typeof MarketingContactRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/setup': typeof AdminSetupRoute
  '/': typeof MarketingIndexRoute
  '/dogs/$dogId': typeof MarketingDogsDogIdRoute
  '/admin/media': typeof AdminDashboardMediaRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/setup': typeof ApiAuthSetupRoute
  '/api/images/$': typeof ApiImagesSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/dogs': typeof MarketingDogsIndexRoute
  '/admin/dogs/new': typeof AdminDashboardDogsNewRoute
  '/admin/applications': typeof AdminDashboardApplicationsIndexRoute
  '/admin/dogs/$dogId/edit': typeof AdminDashboardDogsDogIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_marketing': typeof MarketingRouteRouteWithChildren
  '/admin': typeof AdminRouteRouteWithChildren
  '/admin/_dashboard': typeof AdminDashboardRouteRouteWithChildren
  '/_marketing/about': typeof MarketingAboutRoute
  '/_marketing/application': typeof MarketingApplicationRoute
  '/_marketing/contact': typeof MarketingContactRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/setup': typeof AdminSetupRoute
  '/_marketing/': typeof MarketingIndexRoute
  '/admin/_dashboard/applications': typeof AdminDashboardApplicationsRouteRouteWithChildren
  '/_marketing/dogs/$dogId': typeof MarketingDogsDogIdRoute
  '/admin/_dashboard/media': typeof AdminDashboardMediaRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/setup': typeof ApiAuthSetupRoute
  '/api/images/$': typeof ApiImagesSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/_marketing/dogs/': typeof MarketingDogsIndexRoute
  '/admin/_dashboard/': typeof AdminDashboardIndexRoute
  '/admin/_dashboard/dogs/new': typeof AdminDashboardDogsNewRoute
  '/admin/_dashboard/applications/': typeof AdminDashboardApplicationsIndexRoute
  '/admin/_dashboard/dogs/$dogId/edit': typeof AdminDashboardDogsDogIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/about'
    | '/application'
    | '/contact'
    | '/admin/login'
    | '/admin/setup'
    | '/admin/applications'
    | '/dogs/$dogId'
    | '/admin/media'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/setup'
    | '/api/images/$'
    | '/api/rpc/$'
    | '/dogs/'
    | '/admin/'
    | '/admin/dogs/new'
    | '/admin/applications/'
    | '/admin/dogs/$dogId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/admin'
    | '/about'
    | '/application'
    | '/contact'
    | '/admin/login'
    | '/admin/setup'
    | '/'
    | '/dogs/$dogId'
    | '/admin/media'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/setup'
    | '/api/images/$'
    | '/api/rpc/$'
    | '/dogs'
    | '/admin/dogs/new'
    | '/admin/applications'
    | '/admin/dogs/$dogId/edit'
  id:
    | '__root__'
    | '/_marketing'
    | '/admin'
    | '/admin/_dashboard'
    | '/_marketing/about'
    | '/_marketing/application'
    | '/_marketing/contact'
    | '/admin/login'
    | '/admin/setup'
    | '/_marketing/'
    | '/admin/_dashboard/applications'
    | '/_marketing/dogs/$dogId'
    | '/admin/_dashboard/media'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/setup'
    | '/api/images/$'
    | '/api/rpc/$'
    | '/_marketing/dogs/'
    | '/admin/_dashboard/'
    | '/admin/_dashboard/dogs/new'
    | '/admin/_dashboard/applications/'
    | '/admin/_dashboard/dogs/$dogId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  MarketingRouteRoute: typeof MarketingRouteRouteWithChildren
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  ApiAuthLoginRoute: typeof ApiAuthLoginRoute
  ApiAuthLogoutRoute: typeof ApiAuthLogoutRoute
  ApiAuthSetupRoute: typeof ApiAuthSetupRoute
  ApiImagesSplatRoute: typeof ApiImagesSplatRoute
  ApiRpcSplatRoute: typeof ApiRpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_marketing': {
      id: '/_marketing'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MarketingRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_marketing/': {
      id: '/_marketing/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MarketingIndexRouteImport
      parentRoute: typeof MarketingRouteRoute
    }
    '/admin/setup': {
      id: '/admin/setup'
      path: '/setup'
      fullPath: '/admin/setup'
      preLoaderRoute: typeof AdminSetupRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_marketing/contact': {
      id: '/_marketing/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof MarketingContactRouteImport
      parentRoute: typeof MarketingRouteRoute
    }
    '/_marketing/application': {
      id: '/_marketing/application'
      path: '/application'
      fullPath: '/application'
      preLoaderRoute: typeof MarketingApplicationRouteImport
      parentRoute: typeof MarketingRouteRoute
    }
    '/_marketing/about': {
      id: '/_marketing/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof MarketingAboutRouteImport
      parentRoute: typeof MarketingRouteRoute
    }
    '/admin/_dashboard': {
      id: '/admin/_dashboard'
      path: ''
      fullPath: '/admin'
      preLoaderRoute: typeof AdminDashboardRouteRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/_dashboard/': {
      id: '/admin/_dashboard/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminDashboardIndexRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/_marketing/dogs/': {
      id: '/_marketing/dogs/'
      path: '/dogs'
      fullPath: '/dogs/'
      preLoaderRoute: typeof MarketingDogsIndexRouteImport
      parentRoute: typeof MarketingRouteRoute
    }
    '/api/rpc/$': {
      id: '/api/rpc/$'
      path: '/api/rpc/$'
      fullPath: '/api/rpc/$'
      preLoaderRoute: typeof ApiRpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/images/$': {
      id: '/api/images/$'
      path: '/api/images/$'
      fullPath: '/api/images/$'
      preLoaderRoute: typeof ApiImagesSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/setup': {
      id: '/api/auth/setup'
      path: '/api/auth/setup'
      fullPath: '/api/auth/setup'
      preLoaderRoute: typeof ApiAuthSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/logout': {
      id: '/api/auth/logout'
      path: '/api/auth/logout'
      fullPath: '/api/auth/logout'
      preLoaderRoute: typeof ApiAuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/login': {
      id: '/api/auth/login'
      path: '/api/auth/login'
      fullPath: '/api/auth/login'
      preLoaderRoute: typeof ApiAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_dashboard/media': {
      id: '/admin/_dashboard/media'
      path: '/media'
      fullPath: '/admin/media'
      preLoaderRoute: typeof AdminDashboardMediaRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/_marketing/dogs/$dogId': {
      id: '/_marketing/dogs/$dogId'
      path: '/dogs/$dogId'
      fullPath: '/dogs/$dogId'
      preLoaderRoute: typeof MarketingDogsDogIdRouteImport
      parentRoute: typeof MarketingRouteRoute
    }
    '/admin/_dashboard/applications': {
      id: '/admin/_dashboard/applications'
      path: '/applications'
      fullPath: '/admin/applications'
      preLoaderRoute: typeof AdminDashboardApplicationsRouteRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/admin/_dashboard/applications/': {
      id: '/admin/_dashboard/applications/'
      path: '/'
      fullPath: '/admin/applications/'
      preLoaderRoute: typeof AdminDashboardApplicationsIndexRouteImport
      parentRoute: typeof AdminDashboardApplicationsRouteRoute
    }
    '/admin/_dashboard/dogs/new': {
      id: '/admin/_dashboard/dogs/new'
      path: '/dogs/new'
      fullPath: '/admin/dogs/new'
      preLoaderRoute: typeof AdminDashboardDogsNewRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/admin/_dashboard/dogs/$dogId/edit': {
      id: '/admin/_dashboard/dogs/$dogId/edit'
      path: '/dogs/$dogId/edit'
      fullPath: '/admin/dogs/$dogId/edit'
      preLoaderRoute: typeof AdminDashboardDogsDogIdEditRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
  }
}

interface MarketingRouteRouteChildren {
  MarketingAboutRoute: typeof MarketingAboutRoute
  MarketingApplicationRoute: typeof MarketingApplicationRoute
  MarketingContactRoute: typeof MarketingContactRoute
  MarketingIndexRoute: typeof MarketingIndexRoute
  MarketingDogsDogIdRoute: typeof MarketingDogsDogIdRoute
  MarketingDogsIndexRoute: typeof MarketingDogsIndexRoute
}

const MarketingRouteRouteChildren: MarketingRouteRouteChildren = {
  MarketingAboutRoute: MarketingAboutRoute,
  MarketingApplicationRoute: MarketingApplicationRoute,
  MarketingContactRoute: MarketingContactRoute,
  MarketingIndexRoute: MarketingIndexRoute,
  MarketingDogsDogIdRoute: MarketingDogsDogIdRoute,
  MarketingDogsIndexRoute: MarketingDogsIndexRoute,
}

const MarketingRouteRouteWithChildren = MarketingRouteRoute._addFileChildren(
  MarketingRouteRouteChildren,
)

interface AdminDashboardApplicationsRouteRouteChildren {
  AdminDashboardApplicationsIndexRoute: typeof AdminDashboardApplicationsIndexRoute
}

const AdminDashboardApplicationsRouteRouteChildren: AdminDashboardApplicationsRouteRouteChildren =
  {
    AdminDashboardApplicationsIndexRoute: AdminDashboardApplicationsIndexRoute,
  }

const AdminDashboardApplicationsRouteRouteWithChildren =
  AdminDashboardApplicationsRouteRoute._addFileChildren(
    AdminDashboardApplicationsRouteRouteChildren,
  )

interface AdminDashboardRouteRouteChildren {
  AdminDashboardApplicationsRouteRoute: typeof AdminDashboardApplicationsRouteRouteWithChildren
  AdminDashboardMediaRoute: typeof AdminDashboardMediaRoute
  AdminDashboardIndexRoute: typeof AdminDashboardIndexRoute
  AdminDashboardDogsNewRoute: typeof AdminDashboardDogsNewRoute
  AdminDashboardDogsDogIdEditRoute: typeof AdminDashboardDogsDogIdEditRoute
}

const AdminDashboardRouteRouteChildren: AdminDashboardRouteRouteChildren = {
  AdminDashboardApplicationsRouteRoute:
    AdminDashboardApplicationsRouteRouteWithChildren,
  AdminDashboardMediaRoute: AdminDashboardMediaRoute,
  AdminDashboardIndexRoute: AdminDashboardIndexRoute,
  AdminDashboardDogsNewRoute: AdminDashboardDogsNewRoute,
  AdminDashboardDogsDogIdEditRoute: AdminDashboardDogsDogIdEditRoute,
}

const AdminDashboardRouteRouteWithChildren =
  AdminDashboardRouteRoute._addFileChildren(AdminDashboardRouteRouteChildren)

interface AdminRouteRouteChildren {
  AdminDashboardRouteRoute: typeof AdminDashboardRouteRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
  AdminSetupRoute: typeof AdminSetupRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminDashboardRouteRoute: AdminDashboardRouteRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
  AdminSetupRoute: AdminSetupRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  MarketingRouteRoute: MarketingRouteRouteWithChildren,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  ApiAuthLoginRoute: ApiAuthLoginRoute,
  ApiAuthLogoutRoute: ApiAuthLogoutRoute,
  ApiAuthSetupRoute: ApiAuthSetupRoute,
  ApiImagesSplatRoute: ApiImagesSplatRoute,
  ApiRpcSplatRoute: ApiRpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
